documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"

enhancement:
  - changed-files:
      - any-glob-to-any-file:
          - "fibonacci_series/**"
          - "utils/**"
