#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CASES_PATH = ROOT / "tests" / "cases.json"
IMPLEMENTATIONS_PATH = ROOT / "tests" / "implementations.json"
STATUS_PATH = ROOT / "tests" / "STATUS.md"
COMPILE_TIMEOUT_SECONDS = 60
RUN_TIMEOUT_SECONDS = 10


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def expand(parts: list[str], context: dict[str, str]) -> list[str]:
    return [part.format(**context) for part in parts]


def run_command(
    command: list[str],
    *,
    input_text: str | None = None,
    timeout: int = RUN_TIMEOUT_SECONDS,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=ROOT,
        input=input_text,
        text=True,
        capture_output=True,
        timeout=timeout,
        check=False,
    )


def parse_output(stdout: str) -> list[int]:
    stripped = stdout.strip()
    if not stripped:
        return []
    return [int(token) for token in stripped.split()]


def language_directories() -> list[str]:
    base = ROOT / "fibonacci_series"
    return sorted(path.name for path in base.iterdir() if path.is_dir())


def status_markdown(verified: set[str]) -> str:
    lines = [
        "# Implementation Status",
        "",
        "This file is generated by `utils/test_implementations.py`.",
        "",
        "| Language | Status |",
        "| --- | --- |",
    ]

    for language in language_directories():
        status = "✅ CI verified" if language in verified else "⚪ Community-only"
        lines.append(f"| {language} | {status} |")

    lines.append("")
    return "\n".join(lines)


def validate_tool(command: list[str]) -> str | None:
    executable = command[0]
    if executable.startswith("/") or "/" in executable:
        return None
    if shutil.which(executable) is None:
        return executable
    return None


def test_implementation(
    implementation: dict, cases: dict, temp_root: Path
) -> list[str]:
    language = implementation["language"]
    source = ROOT / implementation["source"]
    errors: list[str] = []

    if not source.is_file():
        return [f"{language}: source file does not exist: {implementation['source']}"]

    build_dir = temp_root / language.replace("+", "p").replace("#", "sharp").replace(" ", "-")
    build_dir.mkdir(parents=True, exist_ok=True)
    binary = build_dir / "fibonacci"

    context = {
        "source": str(source),
        "build_dir": str(build_dir),
        "binary": str(binary),
    }

    compile_command = implementation.get("compile")
    if compile_command:
        command = expand(compile_command, context)
        missing = validate_tool(command)
        if missing:
            return [f"{language}: required tool is not installed: {missing}"]

        try:
            result = run_command(command, timeout=COMPILE_TIMEOUT_SECONDS)
        except subprocess.TimeoutExpired:
            return [f"{language}: compilation timed out after {COMPILE_TIMEOUT_SECONDS}s"]

        if result.returncode != 0:
            details = (result.stderr or result.stdout).strip()
            return [f"{language}: compilation failed: {details}"]

    run_parts = expand(implementation["run"], context)
    missing = validate_tool(run_parts)
    if missing:
        return [f"{language}: required tool is not installed: {missing}"]

    for case in cases["valid"]:
        n = case["input"]
        expected = case["expected"]

        try:
            result = run_command(run_parts, input_text=f"{n}\n")
        except subprocess.TimeoutExpired:
            errors.append(f"{language}: N={n} timed out after {RUN_TIMEOUT_SECONDS}s")
            continue

        if result.returncode != 0:
            errors.append(
                f"{language}: N={n} exited with {result.returncode}: "
                f"{result.stderr.strip()}"
            )
            continue

        try:
            actual = parse_output(result.stdout)
        except ValueError:
            errors.append(
                f"{language}: N={n} produced non-numeric output: {result.stdout!r}"
            )
            continue

        if actual != expected:
            errors.append(f"{language}: N={n} expected {expected}, got {actual}")

    for invalid in cases["invalid"]:
        try:
            result = run_command(run_parts, input_text=f"{invalid}\n")
        except subprocess.TimeoutExpired:
            errors.append(f"{language}: invalid input {invalid!r} timed out")
            continue

        if result.returncode == 0:
            errors.append(
                f"{language}: invalid input {invalid!r} should return a non-zero exit code"
            )

    return errors


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Compile and test canonical Fibonacci implementations."
    )
    parser.add_argument(
        "--language",
        action="append",
        help="Only test a named language (repeatable).",
    )
    parser.add_argument(
        "--write-status",
        action="store_true",
        help="Rewrite tests/STATUS.md after successful tests.",
    )
    args = parser.parse_args()

    cases = load_json(CASES_PATH)
    config = load_json(IMPLEMENTATIONS_PATH)
    all_implementations = config["implementations"]
    implementations = all_implementations

    if args.language:
        requested = set(args.language)
        implementations = [
            item for item in implementations if item["language"] in requested
        ]
        missing = requested - {item["language"] for item in implementations}
        if missing:
            print(
                "Unknown configured language(s): " + ", ".join(sorted(missing)),
                file=sys.stderr,
            )
            return 2

    errors: list[str] = []
    verified: set[str] = set()

    with tempfile.TemporaryDirectory(prefix="fibonacci-tests-") as temp:
        temp_root = Path(temp)

        for implementation in implementations:
            language = implementation["language"]
            print(f"Testing {language}...")
            language_errors = test_implementation(implementation, cases, temp_root)

            if language_errors:
                errors.extend(language_errors)
            else:
                verified.add(language)
                print(f"  PASS {language}")

    if errors:
        print("\nImplementation tests failed:", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    if args.write_status:
        configured = {item["language"] for item in all_implementations}
        STATUS_PATH.write_text(status_markdown(configured), encoding="utf-8")
        print(f"Updated {STATUS_PATH.relative_to(ROOT)}")

    print(f"\nAll {len(verified)} configured implementation(s) passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
